### ISSUE TITLE
Use without extending Activity?

### ISSUE THREAD

**Issue by timhuff** [akhgupta/Android-EasyLocation#3]
I'm trying to use this in a cordova plugin. I can't modify what my Activity extends. Is the purpose of this only to provide a callback interface? Is there a way I can use this without extending Activity?

**Comment by timhuff** [comment]
As an aside, I understand the desire to have this be a situation where it takes care of permissions for you and that requires some pretty close integration with `Activity` but it seems like you're trying to do two things here. I mean, ignoring that I'm making a Cordova plugin, I'm wanting to run this as a `Service`. From that context, I have no access to an `Activity`. This is probably not an uncommon use case. I really like what you've made and the API is great but, personally, it seems like perhaps this should be broken out into two separate libraries - one for permissions and one for location. You only need a `Context` (which is available from within a `Service`) to check for permissions, so it shouldn't be necessary to provide an `Activity` in order to tell the library "get me a location".

**Comment by akhgupta** [comment]
Right now its not possible without extending Activity, I will make this feature available soon.

**Comment by timhuff** [comment]
After making this issue, I actually ended up pulling your source code into my project and modified it to suit my needs. If you'd like, I could make a pull request (without backwards breaking changes).

**Comment by timhuff** [comment]
Just a heads up: I decided to go ahead and move forward with the PR. I should be done with it here shortly. I'll send it your way when I'm done.
